### PR TITLE
Make sure secret key is a proper buffer in the browser

### PR DESCRIPTION
**Pull request by arj03**
With this tribes2 is working in a browser :)

### CODE REVIEW

**Comment by arj03** [comment]
To add a bit more context, sodium-universal is a leaky abstraction :( On native it returns a buffer and in javascript it returns an [Uint8Array](https://github.com/sodium-friends/sodium-javascript/blob/87ff2a56bdc94d2a08c37fd5e5870c2030fc5545/memory.js#L4). Sigh. Sodium-universal actually has exactly this example and uses:

`var rnd = Buffer.allocUnsafe(12) // Cryptographically random data`

instead of sodium malloc. That would also work. The Buffer.from does a copy so it's a tiny more inefficient.

**Comment by arj03** [comment]
Ok, updated to better solution.

**Review by staltz — APPROVED** [review]
I'm fine with this change, but check with Mix too, because he wrote this module.

**Comment by arj03** [comment]
Thanks for taking a look. I shall bug the mix master with no notifications once he is back.

**Comment by arj03** [comment]
@mixmix can you have a look?

**Review by mixmix — APPROVED** [review]
cool, I didn't know about allocUnsafe

**Comment by mixmix** [comment]
thanks @arj03 good to go

**Pull request merged**
